services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - 'env_var/env-compose-backend.env'
    volumes:
      - ./backend:/app
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - 'env_var/env-compose-frontend.env'
    volumes:
      - ./frontend:/app